---
name: Setup Repository and Tools
description: Fetch repository and set up tools (via mise) needed for running reusable workflows.
author: homelab-ops@homelab-ops.com

inputs:
  current_fetch_depth:
    required: false
    type: number
    default: 1
  current_git_ref:
    required: true
    type: string
  current_persist_credentials:
    required: false
    type: boolean
    default: false
  current_repository:
    required: true
    type: string
  current_dir:
    required: false
    type: string
    default: ""
  extra_cache_path:
    required: false
    type: string
    default: ""
  extra_cache_key:
    required: false
    type: string
    default: ""
  mise_ignore_cfg:
    required: false
    type: string
    default: ""
  mise_log_level:
    required: false
    type: string
    default: "info"
  mise_toml:
    required: false
    type: string
    default: ""
  mise_version:
    required: false
    type: string
    # renovate: datasource=github-releases depName=jdx/mise
    default: "v2026.1.8"
  token:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Checkout current
    uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    with:
      fetch-depth: ${{ inputs.current_fetch_depth }}
      path: current
      repository: ${{ inputs.current_repository }}
      ref: ${{ inputs.current_git_ref }}
      persist-credentials: ${{ inputs.current_persist_credentials }}
      token: ${{ inputs.token }}

  - name: Set cache key
    id: cache-key
    shell: bash
    run: echo "cache_key=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"

  - name: Cache - mise
    uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
    with:
      path: ~/.local/share/mise
      # yamllint disable-line rule:line-length
      key: mise-${{ steps.cache-key.outputs.cache_key }}-${{hashFiles('current/mise.toml')}}
      restore-keys: |
        mise-${{ steps.cache-key.outputs.cache_key }}-

  - name: Cache - extra
    if: ${{ inputs.extra_cache_path != '' }}
    uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
    with:
      path: ${{ inputs.extra_cache_path }}
      key: ${{ inputs.extra_cache_key }}-${{ steps.cache-key.outputs.cache_key }}

  - name: Setup mise
    uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
    env:
      MISE_GITHUB_TOKEN: ${{ inputs.token }}
      # yamllint disable-line rule:line-length
      MISE_IGNORED_CONFIG_PATHS: ${{ inputs.mise_ignore_cfg != '' && format('{0}/current/{1}', github.workspace, inputs.mise_ignore_cfg) || '' }}
    with:
      version: ${{ inputs.mise_version }}
      install: true
      cache: false
      experimental: true
      log_level: ${{ inputs.mise_log_level }}
      working_directory: ${{ github.workspace }}/current/${{ inputs.current_dir }}
      mise_toml: ${{ inputs.mise_toml }}
