---
name: Setup Repository and Tools
description: Fetch repository and set up tools (via mise) needed for running reusable workflows.
author: homelab-ops@homelab-ops.com

inputs:
  current_fetch_depth:
    required: false
    type: number
    default: 1
  current_git_ref:
    required: true
    type: string
  current_persist_credentials:
    required: false
    type: boolean
    default: false
  current_repository:
    required: true
    type: string
  extra_cache_path:
    required: false
    type: string
    default: ""
  extra_cache_key:
    required: false
    type: string
    default: ""
  mise_ignore_cfg:
    required: false
    type: string
    default: ""
  mise_log_level:
    required: false
    type: string
    default: "info"
  mise_toml:
    required: true
    type: string
  mise_version:
    required: true
    type: string
  token:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Checkout current
    uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    with:
      fetch-depth: ${{ inputs.current_fetch_depth }}
      path: current
      repository: ${{ inputs.current_repository }}
      ref: ${{ inputs.current_git_ref }}
      persist-credentials: ${{ inputs.current_persist_credentials }}
      token: ${{ inputs.token }}

  - name: Setup default mise configuration
    env:
      MISE_TOML: ${{ inputs.mise_toml }}
      MISE_LOG_LEVEL: ${{ inputs.mise_log_level }}
    shell: bash
    # yamllint disable-line rule:indentation
    run: |
      mkdir -p $GITHUB_WORKSPACE/tools
      cat <<EOF > $GITHUB_WORKSPACE/tools/mise.toml
      ${MISE_TOML}
      EOF

      mkdir -p ~/.config/mise
      ln -s $GITHUB_WORKSPACE/tools/mise.toml ~/.config/mise/config.toml

      if [[ "${MISE_LOG_LEVEL}" == "debug" ]]; then
        cat ~/.config/mise/config.toml
      fi

  - name: Set cache key
    id: cache-key
    shell: bash
    run: echo "cache_key=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"

  - name: Cache - mise
    uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
    with:
      path: ~/.local/share/mise
      # yamllint disable-line rule:line-length
      key: mise-${{ steps.cache-key.outputs.cache_key }}-${{hashFiles('tools/mise.toml')}}-${{hashFiles('current/mise.toml')}}
      restore-keys: |
        mise-${{ steps.cache-key.outputs.cache_key }}-${{hashFiles('tools/mise.toml')}}
        mise-${{ steps.cache-key.outputs.cache_key }}-

  - name: Cache - extra
    if: ${{ inputs.extra_cache_path != '' }}
    uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
    with:
      path: ${{ inputs.extra_cache_path }}
      key: ${{ inputs.extra_cache_key }}-${{ steps.cache-key.outputs.cache_key }}

  - name: Setup mise
    uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
    env:
      MISE_GITHUB_TOKEN: ${{ inputs.token }}
      # yamllint disable-line rule:line-length
      MISE_IGNORED_CONFIG_PATHS: ${{ inputs.mise_ignore_cfg != '' && format('{0}/current/{1}', github.workspace, inputs.mise_ignore_cfg) || '' }}
    with:
      version: ${{ inputs.mise_version }}
      install: true
      cache: false
      experimental: true
      log_level: ${{ inputs.mise_log_level }}
      working_directory: ${{ github.workspace }}/current
