---
# yamllint disable rule:line-length
name: release

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    uses: ppat/github-workflows/.github/workflows/release-please.yaml@72fca5796f7e8f92e60a89226239c1fa197e5c03 # v4.1.0
    secrets:
      app_id: ${{ secrets.HOMELAB_BOT_APP_ID }}
      app_private_key: ${{ secrets.HOMELAB_BOT_APP_PRIVATE_KEY }}
